name: zz_generar_eventos_2

on:
  workflow_call:
  repository_dispatch:
    types: [procesar_eventos_2]  # Tipo de evento personalizado

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 selenium cloudscraper pytz

      # Instalar paquete de idioma español
      - name: Instalar paquete de idioma español
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-es
          sudo locale-gen es_ES.UTF-8
          sudo update-locale LANG=es_ES.UTF-8

      # Configurar identidad de Git
      - name: Configurar identidad de Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Ejecutar el script
      - name: Run Python script
        run: python scripts/generar_eventos_2.py

      # Listar los archivos del repositorio y subdirectorios con detalle de fecha y hora
      - name: List repository files
        run: ls -lR

      # Mostrar el contenido del archivo de log si existe
      - name: Show debug log
        run: |
          if [ -f zz_eventos_2/debug_eventos_2.txt ]; then
            cat zz_eventos_2/debug_eventos_2.txt
          else
            echo "El archivo zz_eventos_2/debug_eventos_2.txt no existe."
          fi

      # Verificar si hay cambios en los archivos
      - name: Check for changes
        id: changes_eventos_2
        run: |
          git add zz_eventos_2/debug_eventos_2.txt zz_eventos_2/eventos_2.csv zz_eventos_2/zz_eventos_2_ott.m3u zz_eventos_2/zz_eventos_2_all_ott.m3u zz_eventos_2_ott.m3u zz_eventos_2_all_ott.m3u
          git status  # Verificación adicional
          if git diff --cached --quiet; then
            echo "No hay cambios para confirmar"
            echo "changes_eventos_2=false" >> $GITHUB_OUTPUT
          else
            echo "Cambios detectados"
            echo "changes_eventos_2=true" >> $GITHUB_OUTPUT
          fi

      # Pull latest changes
      - name: Pull latest changes
        if: steps.changes_eventos_2.outputs.changes_eventos_2 == 'true'
        run: git pull origin main

      # Commit y push
      - name: Commit changes
        if: steps.changes_eventos_2.outputs.changes_eventos_2 == 'true'
        run: |
          echo "Archivos modificados:"
          git status
          echo "Archivos que se incluirán en el commit:"
          git diff --name-only --cached
          git commit -m "Actualización automática desde workflow"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
